//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cyprom.PokemonMasterTrainer.UserInterface.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cyprom.PokemonMasterTrainer.UserInterface.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;Instructions&lt;/title&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;Style.css&quot;&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;h1&gt;Actions&lt;/h1&gt;
        ///		
        ///		&lt;h2&gt;Catching Pok&amp;eacute;mon&lt;/h2&gt;
        ///		&lt;p&gt;
        ///			When you get the chance to catch a Pok&amp;eacute;mon, check the dice on the bottom of the chip.
        ///			These represent the catch rate. If you can roll any of the shown dice, you catch it.
        ///			In case of failure, the chip remains face up on the field.
        ///			If you have special Pok&amp;eacute; Balls (item cards), you can use th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AttackBonus1 {
            get {
                object obj = ResourceManager.GetObject("AttackBonus1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AutoSave_Off {
            get {
                object obj = ResourceManager.GetObject("AutoSave_Off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AutoSave_On {
            get {
                object obj = ResourceManager.GetObject("AutoSave_On", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Battle {
            get {
                object obj = ResourceManager.GetObject("Battle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BlueBubble {
            get {
                object obj = ResourceManager.GetObject("BlueBubble", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BoardMenu {
            get {
                object obj = ResourceManager.GetObject("BoardMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bot {
            get {
                object obj = ResourceManager.GetObject("Bot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;Instructions&lt;/title&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;Style.css&quot;&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;h1&gt;Bots&lt;/h1&gt;
        ///		
        ///		&lt;h2&gt;Players or bots?&lt;/h2&gt;
        ///		&lt;p&gt;
        ///			A physical board game is only any good when there are multiple players.
        ///			Of course, a computer game is a lot of fun with other players as well, but sometimes it&apos;s just not possible to get several people together to play.
        ///			That&apos;s why bots were introduced. Because this digital version of the game is played on a computer [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bots {
            get {
                return ResourceManager.GetString("Bots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BrownDirt {
            get {
                object obj = ResourceManager.GetObject("BrownDirt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CatchSpace {
            get {
                object obj = ResourceManager.GetObject("CatchSpace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Challenge {
            get {
                object obj = ResourceManager.GetObject("Challenge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CitySpace {
            get {
                object obj = ResourceManager.GetObject("CitySpace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Credits {
            get {
                object obj = ResourceManager.GetObject("Credits", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DiceCup_Small {
            get {
                object obj = ResourceManager.GetObject("DiceCup_Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DiceRoller {
            get {
                object obj = ResourceManager.GetObject("DiceRoller", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Disabled {
            get {
                object obj = ResourceManager.GetObject("Disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DungeonOfLegends {
            get {
                object obj = ResourceManager.GetObject("DungeonOfLegends", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Elite {
            get {
                object obj = ResourceManager.GetObject("Elite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Event {
            get {
                object obj = ResourceManager.GetObject("Event", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;Instructions&lt;/title&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;Style.css&quot;&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;h1&gt;Events&lt;/h1&gt;
        ///		
        ///		&lt;h2&gt;Event Cards&lt;/h2&gt;
        ///		&lt;p&gt;
        ///			On your journey, you will encounter many events. But unlike item cards, event cards cannot be saved in a bag.
        ///			When you draw an event card, the event instantly happens. Here is a list of possible events:
        ///		&lt;/p&gt;
        ///		
        ///		&lt;table&gt;
        ///			&lt;tr&gt;
        ///				&lt;td&gt;&lt;img src=&quot;Images/TeamRocket.png&quot;, alt=&quot;Team Rocket&quot; width=&quot;150&quot; /&gt;&lt;/td&gt;
        ///				&lt;td [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EventSpace {
            get {
                object obj = ResourceManager.GetObject("EventSpace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;Instructions&lt;/title&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;Style.css&quot;&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;h1&gt;Evolutions&lt;/h1&gt;
        ///		
        ///		&lt;h2&gt;Evolving&lt;/h2&gt;
        ///		&lt;p&gt;
        ///			Some Pok&amp;eacute;mon evolve into stronger forms. As this game is set up however, you will never actually evolve any of your Pok&amp;eacute;mon.
        ///			Here, you can only get an evolution bonus if you obtain Pok&amp;eacute;mon in the same line of evolution.
        ///			This bonus comes in the form of attack damage for the higher level Pok&amp;eacute; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Evolutions {
            get {
                return ResourceManager.GetString("Evolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Five {
            get {
                object obj = ResourceManager.GetObject("Five", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Fly {
            get {
                object obj = ResourceManager.GetObject("Fly", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Four {
            get {
                object obj = ResourceManager.GetObject("Four", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;Instructions&lt;/title&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;Style.css&quot;&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;h1&gt;Gameplay&lt;/h1&gt;
        ///		
        ///		&lt;h2&gt;Board Menu&lt;/h2&gt;
        ///		&lt;p&gt;
        ///			On the left hand side of the board, a menu displays the current player and a few options.
        ///			To roll and start moving, click the dice cup image in the Player Box.
        ///			If you want to use items first/instead, click on the backpack icon to open your item bag.
        ///			To view your Pok&amp;eacute;mon and their current state, click the Po [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Gameplay {
            get {
                return ResourceManager.GetString("Gameplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;Instructions&lt;/title&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;Style.css&quot;&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;h1&gt;Goal&lt;/h1&gt;
        ///		
        ///		&lt;h2&gt;Power Points&lt;/h2&gt;
        ///		&lt;p&gt;
        ///			The goal of the game is to be the first of all players to become a Pok&amp;eacute;mon Master.
        ///			The first step in achieving this goal, is reaching Indigo Plateau.
        ///			A ferry from Cinnabar Island can take you there, provided that you have accumulated at least 20 power points.
        ///			Power points are a Pok&amp;eacute;mon attribute. The b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Goal {
            get {
                return ResourceManager.GetString("Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GreatBall {
            get {
                object obj = ResourceManager.GetObject("GreatBall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GreenCloth {
            get {
                object obj = ResourceManager.GetObject("GreenCloth", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HighLightedSpace {
            get {
                object obj = ResourceManager.GetObject("HighLightedSpace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Home {
            get {
                object obj = ResourceManager.GetObject("Home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Human {
            get {
                object obj = ResourceManager.GetObject("Human", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;Instructions&lt;/title&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;Style.css&quot;&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;h1&gt;Indigo Plateau&lt;/h1&gt;
        ///		
        ///		&lt;h2&gt;Reaching Indigo Plateau&lt;/h2&gt;
        ///		&lt;p&gt;
        ///			As was explained earlier, you need to make your way to Cinnabar Island. When you get there and you have at least 20 power points, you can take the ferry to Indigo Plateau (on your next turn).
        ///		&lt;/p&gt;
        ///		
        ///		&lt;h2&gt;Wandering around Indigo Plateau&lt;/h2&gt;
        ///		&lt;p&gt;
        ///			Once you have made it there, you will continuousl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Indigo_Plateau {
            get {
                return ResourceManager.GetString("Indigo_Plateau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;Instructions&lt;/title&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;Style.css&quot;&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;h1&gt;Overview&lt;/h1&gt;
        ///		&lt;ol&gt;
        ///			&lt;li&gt;&lt;a href=&quot;Introduction.html&quot;&gt;Introduction&lt;/a&gt;&lt;/li&gt;
        ///			&lt;li&gt;&lt;a href=&quot;Setup.html&quot;&gt;Setup&lt;/a&gt;&lt;/li&gt;
        ///			&lt;li&gt;&lt;a href=&quot;Start.html&quot;&gt;Start&lt;/a&gt;&lt;/li&gt;
        ///			&lt;li&gt;&lt;a href=&quot;Bots.html&quot;&gt;Bots&lt;/a&gt;&lt;/li&gt;
        ///			&lt;li&gt;&lt;a href=&quot;Gameplay.html&quot;&gt;Gameplay&lt;/a&gt;&lt;/li&gt;
        ///			&lt;li&gt;&lt;a href=&quot;Spaces.html&quot;&gt;Spaces&lt;/a&gt;&lt;/li&gt;
        ///			&lt;li&gt;&lt;a href=&quot;Actions.html&quot;&gt;Actions&lt;/a&gt;&lt;/li&gt;
        ///			&lt;li&gt;&lt;a href=&quot;Evolutio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;Instructions&lt;/title&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;Style.css&quot;&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;h1&gt;Introduction&lt;/h1&gt;
        ///		
        ///		&lt;h2&gt;Welcome&lt;/h2&gt;
        ///		&lt;p&gt;
        ///			Welcome to the world of Pok&amp;eacute;mon!
        ///			&lt;br /&gt;Unfortunately, the world of Pok&amp;eacute;mon is not real, and so the sentence above is often heard in a digital environment.
        ///			However, Pok&amp;eacute;mon Master Trainer is a board game that can be physically obtained. This introduction will explain the concept and changes made i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Investigation {
            get {
                object obj = ResourceManager.GetObject("Investigation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Item {
            get {
                object obj = ResourceManager.GetObject("Item", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ItemBag {
            get {
                object obj = ResourceManager.GetObject("ItemBag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ItemBag_Small {
            get {
                object obj = ResourceManager.GetObject("ItemBag_Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ItemFinder1 {
            get {
                object obj = ResourceManager.GetObject("ItemFinder1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;Instructions&lt;/title&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;Style.css&quot;&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;h1&gt;Items&lt;/h1&gt;
        ///		
        ///		&lt;h2&gt;Item Cards&lt;/h2&gt;
        ///		&lt;p&gt;
        ///			During your adventure, you will find certain items. This can happen when you win a Pok&amp;eacute;mon battle, when you arrive in a city, or even as an event.
        ///			You can benefit from these items in different ways. The list below sums up the possibilities:
        ///		&lt;/p&gt;
        ///		
        ///		&lt;table&gt;
        ///			&lt;tr&gt;
        ///				&lt;td&gt;&lt;img src=&quot;Images/AttackBonus1.png&quot;, a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Kanto {
            get {
                object obj = ResourceManager.GetObject("Kanto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Log_Off {
            get {
                object obj = ResourceManager.GetObject("Log_Off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Log_On {
            get {
                object obj = ResourceManager.GetObject("Log_On", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Music_Off {
            get {
                object obj = ResourceManager.GetObject("Music_Off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Music_On {
            get {
                object obj = ResourceManager.GetObject("Music_On", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Oak {
            get {
                object obj = ResourceManager.GetObject("Oak", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap One {
            get {
                object obj = ResourceManager.GetObject("One", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Options {
            get {
                object obj = ResourceManager.GetObject("Options", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlateauMovement {
            get {
                object obj = ResourceManager.GetObject("PlateauMovement", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerSelection {
            get {
                object obj = ResourceManager.GetObject("PlayerSelection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pokedex {
            get {
                object obj = ResourceManager.GetObject("Pokedex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pokedex_Small {
            get {
                object obj = ResourceManager.GetObject("Pokedex_Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PokeDoll {
            get {
                object obj = ResourceManager.GetObject("PokeDoll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PokemonCenter {
            get {
                object obj = ResourceManager.GetObject("PokemonCenter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Potion {
            get {
                object obj = ResourceManager.GetObject("Potion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PowerPoints {
            get {
                object obj = ResourceManager.GetObject("PowerPoints", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RedRug {
            get {
                object obj = ResourceManager.GetObject("RedRug", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ScreenLock_Off {
            get {
                object obj = ResourceManager.GetObject("ScreenLock_Off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ScreenLock_On {
            get {
                object obj = ResourceManager.GetObject("ScreenLock_On", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;Instructions&lt;/title&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;Style.css&quot;&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;h1&gt;Setup&lt;/h1&gt;
        ///		
        ///		&lt;h2&gt;Board&lt;/h2&gt;
        ///		&lt;p&gt;
        ///			The board is loaded with its initial Pok&amp;eacute;mon chips. Random chips are placed on the board on the foreseen spots with their corresponding color.
        ///			Not all chips will be in play, but they can be added later on. The exception are yellow chips. All 5 legendary Pok&amp;eacute;mon are placed in the Dungeon of Legends.
        ///		&lt;/p&gt;
        ///		
        ///		&lt;h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Six {
            get {
                object obj = ResourceManager.GetObject("Six", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sound_Off {
            get {
                object obj = ResourceManager.GetObject("Sound_Off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sound_On {
            get {
                object obj = ResourceManager.GetObject("Sound_On", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;Instructions&lt;/title&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;Style.css&quot;&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;h1&gt;Spaces&lt;/h1&gt;
        ///		
        ///		&lt;h2&gt;Cities and Towns&lt;/h2&gt;
        ///		&lt;p&gt;
        ///			Cities and Towns allow multiple players to stand together.
        ///			In most of them, you will have the chance to draw 2 item cards.
        ///			In a select few, you can use a Pok&amp;eacute;mon Center to revive knocked out Pok&amp;eacute;mon.
        ///			Either revive a single Pok&amp;eacute;mon (guaranteed) or try to roll higher than a 4 to revive all o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Spaces {
            get {
                return ResourceManager.GetString("Spaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Splash {
            get {
                object obj = ResourceManager.GetObject("Splash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;Instructions&lt;/title&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;Style.css&quot;&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;h1&gt;Start&lt;/h1&gt;
        ///		
        ///		&lt;h2&gt;New Game&lt;/h2&gt;
        ///		&lt;h3&gt;Player Selection&lt;/h3&gt;
        ///		&lt;p&gt;
        ///			When a new game is started, the first thing to do is select the amount and types of players.
        ///			The Player Selection screen shows 3 squares, each representing a single player.
        ///			Originally, all three of these squares have a human player icon, which means that there will be 3 human players.
        ///			You c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StarterSelection {
            get {
                object obj = ResourceManager.GetObject("StarterSelection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * {
        ///	font-family: &quot;High Tower Text&quot;, Tower, sans-serif;
        ///	background-color: rgb(200, 200, 200);
        ///}
        ///
        ///a {
        ///    color: blue;
        ///}
        ///
        ///h1 {
        ///	text-decoration: underline;
        ///	font-size: 46px;
        ///}
        ///
        ///h2 {
        ///	margin-top: 20px;
        ///	margin-bottom: -10px;
        ///}
        ///
        ///h3 {
        ///	margin-bottom: -15px;
        ///}
        ///
        ///td {
        ///	vertical-align: top;
        ///	padding-bottom: 10px;
        ///}
        ///
        ///dt {
        ///	font-size: 18px;
        ///	font-weight: bold;
        ///}
        ///
        ///dd {
        ///	margin-left: 0;
        ///	margin-bottom: 10px;
        ///}
        ///
        ///.mover {
        ///	margin-top: 10px;
        ///	margin-bottom: 10px;
        ///	padding: 10px;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TeamRocket {
            get {
                object obj = ResourceManager.GetObject("TeamRocket", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Three {
            get {
                object obj = ResourceManager.GetObject("Three", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ThreeSet {
            get {
                object obj = ResourceManager.GetObject("ThreeSet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Trade {
            get {
                object obj = ResourceManager.GetObject("Trade", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Two {
            get {
                object obj = ResourceManager.GetObject("Two", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TwoSet {
            get {
                object obj = ResourceManager.GetObject("TwoSet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
